# Generated by Django 5.1.7 on 2025-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
